### ISSUE TITLE
Conditional values

### ISSUE THREAD

**Issue by fbrnc** [AOEpeople/StackFormation#6]
Sometimes a var/parameter needs different values depending on other variables (especially if you're using placeholders in your stacknames like `app-{env:Environment}-build`

Something like this should be supported:

```
  - stackname: 'app-{env:Environment}-build'
    template: 'build.template'
    parameters:
      KeyName:
        '{env:Environment}==prod': 'MyProdKey'
        '{env:Environment}==stage': 'MyStageKey'
        'default': 'MyDevKey'
```
